export enum UserStatus {
    ACTIVE = "ACTIVE",
    WARNING = "WARNING",
    BLOCKED = "BLOCKED",
    RESTRICTED = "RESTRICTED",
    TEMP_LOCKED = "TEMP_LOCKED",
    LOCKED = "LOCKED",
    HIDDEN = "HIDDEN",
    DELETED = "DELETED",
}
